### ISSUE TITLE
[REQUEST] C-styled int/real literal distinction

### ISSUE THREAD

**Issue by nazjun** [Natashi/Touhou-Danmakufu-ph3sx-2#12]
I requested this informally before, but I would still love to see this as a feature once compatibility is no longer an issue (and personally, I don't expect it to be that big a deal in the end).

Basically, do away with the `i` suffix and have the presence of a decimal point be what distinguishes integers from real numbers.
This would also encompass all hexadecimal and binary literals, which... don't really have a reason not to be int types?

**Comment by Natashi** [comment]
Added support for explicit type declarations with [commit 03c028c](https://github.com/Natashi/Touhou-Danmakufu-ph3sx-2/commit/03c028c67c41cf942e1b55f8a89c7583fcd4db2e)
