### ISSUE TITLE
[BUG] ObjRender_SetAlpha doesn't work on sprite lists that have had their vertexes closed

### ISSUE THREAD

**Issue by TTBD** [Natashi/Touhou-Danmakufu-ph3sx-2#13]
Like the title says, if you use "ObjSpriteList2D_CloseVertex" on a sprite list, ObjRender_SetAlpha no longer does anything to it.

**Comment by Natashi** [comment]
Fixed as of commit [826277e](https://github.com/Natashi/Touhou-Danmakufu-ph3sx-2/commit/826277eb0bc071a208aade9f63c7269ce5417b95).
