### ISSUE TITLE
Stuttering during gameplay

### ISSUE THREAD

**Issue by Matoneto** [Natashi/Touhou-Danmakufu-ph3sx-2#16]
I get repeating stutters during gameplay even when there is not much happening. The FPS are not dropping.

I tried:

- Changing settings in the config program, vsync and so on.
- Changing vsync and FPS Limit via the graphics card driver.
- Enable Compatibility Mode in Windows.

Nothing helped. Other games run fine. This also happens with the original danmakufu.

**Comment by Matoneto** [comment]
Did some more testing and I can verify it on another computer which shows the exact same. Both are on Windows 10.

It seems to be a problem with vsync in the application. I could only find one danmakufu version where there are no stutters. It's the one bundled with this game: [https://www.bulletforge.org/u/team-alternative-snding/p/dong-fang-meng-jiu-shi-glory-of-deep-skies](url). They call it Re:Danmakufu and i tried to find out more about it but didn't find anything. I am new to danmakufu so maybe thats why I couldn't find anything.

This game offers a vsync option in their config program. When this is on everything runs butter smooth even when a lot is going on. When it is switched off its exactly the same with the stutters.

I hope that helps.

**Comment by Matoneto** [comment]
I tested on a completely different system which has Windows 7 on it and uses AMD CPU and GPU compared to the other system with Nvidia and Intel parts. Same problem. Stuttering is not so evenly distributed but instead sometimes happens in chunks.

I guess this is not a problem with my machine(s) but really a problem in the software.

**Comment by Matoneto** [comment]
I looked at many 60 FPS videos on YT of different danmakufu games / scripts and it seems that there are also these stutters in the videos. I made sure that there are no dropped frames on my end. So either it's the videos or stutters are normal with this engine? I hope someone can give some feedback on this.

**Comment by Natashi** [comment]
Can you record a footage? "Stuttering" is too broad of a word when it comes to this.

**Comment by Natashi** [comment]
Closed due to lack of response.
