### ISSUE TITLE
[BUG] SetShotIntersectionCircle and SetShotIntersectionLine don't function at all

### ISSUE THREAD

**Issue by TTBD** [Natashi/Touhou-Danmakufu-ph3sx-2#17]
This has been an issue since the original ph3, but after a certain ph3 update both of these functions stopped working for some reason.

For context, both functions are here:
https://sparen.github.io/ph3tutorials/docs_standard.html#fxn_SetShotIntersectionCircle

**Comment by Natashi** [comment]
[Fixed.](https://github.com/Natashi/Touhou-Danmakufu-ph3sx-2/commit/8f04db349c48b1c5ac90776f85351a439947a82b)
