### ISSUE TITLE
[Feature request] Forbid enemy shot

### ISSUE THREAD

**Issue by benderama3** [Natashi/Touhou-Danmakufu-ph3sx-2#2]
Hi,

Here a function that can be useful as I didn't find an alternative:

**Feature**:
Add a function similar to ObjMove_SetProcessMovement or SetForbidPlayerShot to prevent an enemy from using shot-related routines 

Thanks

**Comment by Natashi** [comment]
It's a little too specific to be a built-in feature, and it can easily be done from the script side, so I don't really see a reason to add it.
