### ISSUE TITLE
More freedom for determining what the engine does when the user clicks off of the window

### ISSUE THREAD

**Issue by IncandescenceSy** [Natashi/Touhou-Danmakufu-ph3sx-2#22]
When the window is unfocused, the engine completely freezes. Well, almost completely. Sound, however, does not. I've heard that Danmakufu's sound handling is really garbage and was slapped on top of everything else at the last minute, which could explain this disparity, as well as why it's so limited (there are many, many feature requests I have relating to sound, but since sound is apparently so broken in Danmakufu, I'll refrain from making them under the assumption that the addition of anything helpful would likely require rewriting all of the engine's sound handling, and you probably wouldn't want to do that). However, there are many issues with the sound not freezing: it can destroy music sync, make it more annoying to just "pause" the game and just ignore it for a bit (since some scripters fail to make actually pausing pause the music, or you can't pause during certain scenes), etc. Ergo, we should have the ability to decide what we want to happen when you click off the window. It should be a function, and not a .def parameter, so that it can be changed in the middle of the operation (use case: you may want everything to freeze during most of the game, but during the music room you'd rather nothing froze so that the player could use that to listen to it in the background).

**Comment by Natashi** [comment]
Added in commit [fedc1fbe](https://github.com/Natashi/Touhou-Danmakufu-ph3sx-2/commit/fedc1fbe44703c622e15de0b107ded36aae0ff91) and [404e83ae](https://github.com/Natashi/Touhou-Danmakufu-ph3sx-2/commit/404e83aeb7cfbf97931db7b625c3e73dfffe62a6)
