### ISSUE TITLE
The same sound should be allowed to be played multiple at the same time

### ISSUE THREAD

**Issue by AlufeWasTaken** [Natashi/Touhou-Danmakufu-ph3sx-2#26]
I have a sound object A which is 4 seconds long, I want to play it with a 2 seconds delay, resulting in each new call killing the sound of the old call. I think a function would be nice, which gives soundobjects the permission to not cancel them out.

I noticed it wont help creating multiple different objects, as long the are using the path of the sound origin sound, meaning I must copy paste the same sound like 4 times, if I want to play it 4 times in short perios as an example.

**Comment by Natashi** [comment]
Feature is now implemented in commit [6b08419](https://github.com/Natashi/Touhou-Danmakufu-ph3sx-2/commit/6b0841930e364389b9179b959ba7e4b05f3ece9d).
