### ISSUE TITLE
PH3SX crashes during startup

### ISSUE THREAD

**Issue by MakutaMatara** [Natashi/Touhou-Danmakufu-ph3sx-2#27]
So I downloaded PH3SX on my desktop, I run both the normal and legacy versions but it crashes right at startup. I didn't do any modifications from it, it just crashes. 

My PC specs: 
Device name    DESKTOP-JD47021
Processor    Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz   3.60 GHz
Installed RAM    4.00 GB
Device ID    B8F9DE81-837B-4E2B-8A35-D10479018D7E
Product ID    00327-30779-11784-AAOEM
System type    64-bit operating system, x64-based processor
Pen and touch    No pen or touch input is available for this display

Edition    Windows 10 Home Single Language
Version    20H2
Installed on    ‎08/‎04/‎2021
OS build    19042.985
Experience    Windows Feature Experience Pack 120.2212.2020.0

**Comment by Natashi** [comment]
I do not want to know your PC model.
Give me:
- CPU
- Graphics card
- OS
- RAM
- DirectX version

**Comment by Natashi** [comment]
Closed due to lack of response.
