### ISSUE TITLE
ObjSound_IsPlaying no longer works properly

### ISSUE THREAD

**Issue by TTBD** [Natashi/Touhou-Danmakufu-ph3sx-2#34]
ObjSound_IsPlaying no longer works as it should in version 1.30a; it seems to only return true for a frame before it then returns false (shown in the screenshot). The sound I used this with was Touhou's regular pause sound effect.
![screenshot](https://user-images.githubusercontent.com/31350120/127087042-138378a5-1125-465c-b0dd-0abd0364ffec.png)

**Comment by Natashi** [comment]
This issue has actually been present since vanilla ph3.

Fixed as of commit [df3c48d](https://github.com/Natashi/Touhou-Danmakufu-ph3sx-2/commit/df3c48d248aeb1342cb5eec41d3ea803f4481242).
