### ISSUE TITLE
[BUG] Particle list instances not scaling + rotating properly

### ISSUE THREAD

**Issue by nazjun** [Natashi/Touhou-Danmakufu-ph3sx-2#4]
When you set the Z angle of an instance, as well as two distinct X and Y scales, it appears that the scaling is applied _after_ the rotation, as the rotated shape will remain stretched or squished horizontally or vertically instead of the scale change "rotating" with the Z angle as it does in the case of most render objects.

See the attachment for an example of what I mean.
![rectangl](https://user-images.githubusercontent.com/31663251/94223235-6d0c0600-febd-11ea-830c-36a222c582d8.png)

**Comment by Natashi** [comment]
Fixed.
