### ISSUE TITLE
Build instructions for libraries/ext are shit, rewrite them.

### ISSUE THREAD

**Issue by WishMakers0** [Natashi/Touhou-Danmakufu-ph3sx-2#63]
./library/.Information.txt ->
```Missing libraries:
	[zlib 1.2.11] 		-> https://www.zlib.net/
		zlibstatic.lib or zlibdynamic.lib (with zlib.dll)
			- Release configuration
	[libogg 1.3.4]		-> https://xiph.org/
		ogg_static.lib
			- Release configuration
	[libvorbis 1.3.6]	-> https://xiph.org/
		vorbis_static.lib
			- Release configuration
		vorbisfile_static.lib
			- Release configuration
```
This tells me nothing on how you expect these libraries to be built, nor does it specify what the file you will receive from compiling is.
When it takes me 2 hours despite having everything I need and Visual Studio can't provide a useful error message, and nothing in your documentation is helpful, and I have to get libraries precompiled by Naudiz, I think that's a fucking problem.

./source/ext/.Information.txt ->
```Missing header files:
	[zlib 1.2.11] 		-> https://www.zlib.net/
		zlib/zconf.h
		zlib/zlib.h
	[libogg 1.3.4]		-> https://xiph.org/
		ogg/ogg.h
		ogg/os_types.h
	[libvorbis 1.3.6]	-> https://xiph.org/
		vorbis/codec.h
		vorbis/vorbisfile.h
```
Couldn't hurt to at least tell the reader where to acquire these files in each archive, but less of a priority.

**Comment by WishMakers0** [comment]
![image](https://user-images.githubusercontent.com/35705292/147166290-6f048203-a275-43d4-9c13-2214a2b55302.png)
As soon as this is implemented, I'll close this issue myself.

**Comment by Natashi** [comment]
[Boop.](https://github.com/Natashi/Touhou-Danmakufu-ph3sx-2/commit/cfbbc6f3808ceb2ecd95f848a87306730126ef9f)
