### ISSUE TITLE
It's a bad thing because of licence

### ISSUE THREAD

**Issue by pa106** [Natashi/Touhou-Danmakufu-ph3sx-2#70]
[Original PH3SX](https://web.archive.org/web/*/https://github.com/WishMakers0/Touhou-Danmakufu-ph3sx) is [no licence](https://choosealicense.com/no-permission),it [make its copyright management chaotic](https://choosealicense.com/no-permission) and [it even can‘t edit,build and run](https://www.gnu.org/licenses/license-list.html#NoLicense) in some countries.so i think you must delete this git repo and tell others to delete games using PH3SX,because [Original PH3SX git repo](https://web.archive.org/web/*/https://github.com/WishMakers0/Touhou-Danmakufu-ph3sx) is deleted and it hurts Danmakufu's futures,and if [PH3.5](https://github.com/WishMakers0/Danmakufu-Woo-Edition) have any codes form PH3SX(both [Original](https://web.archive.org/web/*/https://github.com/WishMakers0/Touhou-Danmakufu-ph3sx) and this),games using PH3.5 must delete,too.Now it's a best way to make danmakufu have good future,but Its code cannot be used on any Modified Danmakufu’s source code,But just writing code that does the same thing but is more complex than the code in PH3SX can give Danmakufu a better future.（I believe there can be)(You should have added a license to [Original PH3SX git repo](https://web.archive.org/web/*/https://github.com/WishMakers0/Touhou-Danmakufu-ph3sx) while it was still there, but you didn't, and you regretted it was too late.)

**Comment by Natashi** [comment]
I do not give a flying shit.

**Comment by Natashi** [comment]
Re-opening just for the hell of it.

**Comment by Demonese** [comment]
lol

**Comment by pa106** [comment]
Yes, but not just you. In fact, in the original ph3sx, there are already three people's contributions, the first time is a (probably) unregistered user contributed .gitignore and a file that was not used in actual development
, but neither indicates its license, which means that without the consent of unregistered users, no one has the right to modify .gitignore and any files contributed by that user, and then when wish contributes to this project, wish also becomes the copyright of this project. People, after that, the original ph3sx is deleted, and the new ph3sx has the copyright of others, and those people are the copyright owners of the new ph3sx, but not the original ph3sx, so using the open source license for ph3sx needs to be restored first The source code of the original ph3sx but without files contributed by unregistered users and using an expat-style license for the original ph3sx with the copyright texts of all original ph3sx copyright owners (no unregistered users) through a cooperative commit, and then in the new Remove .gitignore on ph3sx and replace it with a modified expat-style license for the original ph3sx with all copyright owners (no unregistered users) of the original ph3sx and the new ph3sx after the modification provided by github, There are also licenses in the "/" directory as much as possible, and you have contributed from 2019 to the present. Wish started and terminated contributions in 2020. You should be clear about this, but I still recommend that you delete it, because The latter is much simpler than the former.

**Comment by Natashi** [comment]
Do you really think any of the people involved gives a flying fuck about copyright about this project in particular? You can use ph3sx code to build a ballistic missile launcher for all I care.
If you're that anal about copyright, then don't get involved with ph3sx.

**Comment by nazjun** [comment]
The girls are fighting!!! 🤼‍♀️

**Comment by WishMakers0** [comment]
@pa106 Hi, person who owns the Danmakufu Woo repo and the ph3sx repo you listed.  First of all, the ph3sx repo you listed is a fork of the original, which was also owned by Natashi.  It was deleted because the original solution file got messed up and needed to be remade.  Second of all, none of this matters.  If you're going to continue raving on about copyright for a very clearly open source project that was abandoned by its previous owner, you are out of your mind.  
I don't even know why I am humoring this, but here's the license that Danmakufu's original source code falls under.
![image](https://user-images.githubusercontent.com/35705292/153634860-8654a003-70fb-4a70-ba8c-fae41f7e2ace.png)
Please stop fighting this.  The fact that your Github account is so new and this is the first issue you've ever submitted is telling.

**Comment by pa106** [comment]
Do you looked carefully? I suggest natashi to delete the source code of the current ph3sx based on the source code of the original ph3sx, instead of restoring the source code of the original ph3sx. Also NSYL is a permissive license, anyone can modify it, as long as it doesn't come with its agreement, it is privatized, and the licensing method of the danmakufu ph3 license itself is problematic unless you or anyone send email to TouhouGC using Japanese or   both Japanese and English to ask him to change the license to mpl2 or gpl2 or later above and have it include a local copy of its license in the ph3 source code, otherwise there is no reason for ph3sx to open source and continue.

The last commit was directly translated using Google Translate, which may be the reason why you misunderstood my original meaning.

**Comment by Natashi** [comment]
This is fucking nuts, you're actually delusional. This was entertaining for only the first few comments, now this is just stupid.
Please, go bother someone else with all this shit. We do not have the time nor the patience for this.
