### ISSUE TITLE
DnhConfig compile issue

### ISSUE THREAD

**Issue by Demonese** [Natashi/Touhou-Danmakufu-ph3sx-2#72]
![1](https://user-images.githubusercontent.com/57629614/156300058-8fec1ecf-f8d3-4608-b06c-93844086ef47.jpg)
![image](https://user-images.githubusercontent.com/57629614/156300107-e839c3f3-1500-4aca-a504-039c6bc49de2.png)

**Comment by Natashi** [comment]
Ah fuck, my bad.
[There.](https://github.com/Natashi/Touhou-Danmakufu-ph3sx-2/commit/ae46f3b016ddd962fa1016178b5bbf5bb9ee662a)
