### ISSUE TITLE
LETTER

### ISSUE THREAD

**Issue by bitch104** [Natashi/Touhou-Danmakufu-ph3sx-2#73]
Nts,Wish,Nd:
    Hello, I didn't say copyright is jack shit, but tell you what I think is a reasonable solution, because the NSYL license does have some content that is unacceptable, such as its first line will use this open source software to call For "Freeware", if the meaning is extended, it can be understood that it does not allow DNH ph3 and its source code to be obtained for a fee, and its last line of giving up its copyright statement will make mkm unable to replace the license for DNH ph3, so it is extremely It's probably not two-way compatible with other licenses, code released under a permissive license can be merged with it, but it itself cannot be changed to another license, fortunately he didn't put a local copy of this license in the source code, So now you guys can email mkm and ask him to change the license and add a local copy of the license inside the released source, I recommend you guys recommend "(L)GPL3 or later" to him as that would also solve ph3sx copyright issues. I hope you can listen to me and do so.

**Comment by Natashi** [comment]
If it bothers you so much, do it yourself.
Let me tell you first that it's very likely that he doesn't give a fuck. Danmakufu is an abandonware, it has been since 2015.

Please. Stop bothering us with this bullcrap.
