### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by mm184** [Natashi/Touhou-Danmakufu-ph3sx-2#75]
Dear Natashi:
       I don't think you need to open source this because most people who use this generally don't contribute to the project, so I suggest you keep it private and give him (or her) access if anyone wants to contribute to the project , and the year the software license is written should be counted from the year you prepared this license to the year of your last contribution, and anyone who uses "Pull request" and any other updated files before the software license is applied If you don't give up the copyright, it means to keep the copyright by default, and it is not a copyright transfer, so you still need their consent, and you need to mark their name and the year they agreed to use the license on the license (and they are in this The software indicates the year of contribution after the license), unless the license does not require the name of all copyright holders and the year they contributed, I still recommend that you remove this or the original git repository is published and the license is indicated, because Open source is mainly about keeping it open source as it is, not keeping it private for any other reason.

**Comment by Natashi** [comment]
Please stop interacting with this repository. I can recognize your name changes.
