### ISSUE TITLE
[BUG] If Set2DCameraAngleZ is set to anything except 0, the screen flips vertically and horizontally

### ISSUE THREAD

**Issue by TTBD** [Natashi/Touhou-Danmakufu-ph3sx-2#9]
Like the title says, if Set2DCameraAngleZ is set to anything except 0 the screen flips vertically and horizontally.
This also results in Set2DCameraRatioX and Set2DCameraRatioY not working as intended; sometimes it may result in the camera going off-screen.

**Comment by Natashi** [comment]
Fixed the Set2DCameraAngleZ part, still not sure about Set2DCameraRatioX/Y.
